import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, ArrowRight, Check, ChevronRight, CircleDollarSign, Database, LayoutDashboard, LogOut, Menu, Package, Plus, RefreshCw, Settings, ShoppingBag, Store, Truck, Users, X } from 'lucide-react';
import { api, setToken } from './api';
import './style.css';

const money = (value) => `₦${Number(value || 0).toLocaleString('en-NG')}`;
function Login({ onAuthenticated }) { const [step, setStep] = useState('password'); const [form, setForm] = useState({ username: '', password: '', otp: '' }); const [error, setError] = useState(''); const change = (key) => (event) => setForm({ ...form, [key]: event.target.value }); const submit = async (event) => { event.preventDefault(); setError(''); try { if (step === 'password') { await api.login(form); setStep('otp'); } else { const result = await api.otp(form); setToken(result.accessToken); onAuthenticated(result.user); } } catch (e) { setError(e.message); } }; return <main className="auth-shell"><div className="auth-card"><div className="mark">PS</div><p className="kicker">PRIMESTAR / CONTROL ROOM</p><h1>{step === 'password' ? 'Welcome back.' : 'Check your inbox.'}</h1><p className="muted">{step === 'password' ? 'Sign in to manage the live delivery operation.' : 'Enter the six-digit code sent to the configured admin email.'}</p><form onSubmit={submit}>{step === 'password' ? <><label>Username<input required value={form.username} onChange={change('username')} autoComplete="username" /></label><label>Password<input required type="password" value={form.password} onChange={change('password')} autoComplete="current-password" /></label></> : <label>6-digit verification code<input required inputMode="numeric" pattern="[0-9]{6}" maxLength="6" value={form.otp} onChange={change('otp')} /></label>}{error && <p className="error">{error}</p>}<button className="primary full">{step === 'password' ? 'Continue' : 'Verify access'} <ArrowRight size={17} /></button></form></div></main>; }
function Sidebar({ section, setSection, logout }) { const links = [['overview','Overview',LayoutDashboard],['orders','Orders',ShoppingBag],['vendors','Vendors',Store],['products','Products',Package],['riders','Riders',Truck],['requests','Requests',Activity],['settings','Settings',Settings]]; return <aside className="sidebar"><div className="admin-brand"><span>PS</span><div><b>PRIMESTAR</b><small>ADMIN / CONTROL</small></div></div><nav>{links.map(([id,label,Icon]) => <button className={section === id ? 'active' : ''} key={id} onClick={() => setSection(id)}><Icon size={18} />{label}</button>)}</nav><button className="logout" onClick={logout}><LogOut size={17} />Sign out</button></aside>; }
function Stat({ label, value, icon: Icon, accent }) { return <div className={`stat ${accent || ''}`}><span className="stat-icon"><Icon size={18} /></span><small>{label}</small><strong>{value}</strong></div>; }
function Overview({ data, refresh }) { return <><div className="page-title"><div><p className="kicker">LIVE OPERATION</p><h1>Good morning, admin.</h1><p className="muted">A quick read on what needs attention right now.</p></div><button className="outline" onClick={refresh}><RefreshCw size={16} />Refresh</button></div><div className="stats-grid"><Stat label="Orders" value={data.orders} icon={ShoppingBag} /><Stat label="Pending payments" value={data.pendingPayments} icon={CircleDollarSign} accent="gold" /><Stat label="Active riders" value={data.activeRiders} icon={Truck} /><Stat label="Live vendors" value={data.vendors} icon={Store} /></div><div className="dashboard-grid"><section className="panel"><div className="panel-heading"><div><p className="kicker">ATTENTION</p><h2>Payment queue</h2></div><ChevronRight size={18} /></div><div className="queue-row"><span className="queue-dot gold" /><div><b>{data.pendingPayments} orders awaiting confirmation</b><small>Review bank alerts before dispatch.</small></div></div><div className="queue-row"><span className="queue-dot green" /><div><b>{data.confirmedPayments} payments confirmed</b><small>Float eligibility can now be considered.</small></div></div></section><section className="panel"><div className="panel-heading"><div><p className="kicker">CATALOG</p><h2>Database coverage</h2></div><Database size={18} /></div><div className="coverage"><div><span>Products</span><b>{data.products}</b></div><div><span>Open packages</span><b>{data.packageRequests}</b></div><div><span>Open GET4ME</span><b>{data.get4meRequests}</b></div></div></section></div></>; }
function ResourceTable({ resource, title, rows, onRefresh, onCreate, onAction }) { return <section className="panel resource-panel"><div className="panel-heading"><div><p className="kicker">DATABASE / {resource.toUpperCase()}</p><h2>{title}</h2></div><div className="panel-actions"><button className="outline" onClick={onRefresh}><RefreshCw size={15} />Refresh</button>{onCreate && <button className="primary" onClick={onCreate}><Plus size={16} />Add</button>}</div></div>{rows.length ? <div className="table-wrap"><table><thead><tr><th>Name / ID</th><th>Status</th><th>Updated</th><th /></tr></thead><tbody>{rows.map((row) => <tr key={row._id || row.orderId}><td><b>{row.name || row.orderId || row.request || row.username}</b><small>{row.type || row.phone || row.paymentState || ''}</small></td><td><span className="status">{row.status || (row.active === false ? 'inactive' : 'active')}</span></td><td>{new Date(row.updatedAt || row.createdAt).toLocaleDateString('en-NG')}</td><td>{onAction && <button className="row-action" onClick={() => onAction(row)}><ChevronRight size={17} /></button>}</td></tr>)}</tbody></table></div> : <div className="empty"><Database size={23} /><b>No records yet</b><span>Records created in MongoDB will appear here.</span></div>}</section>; }
function CreateVendor({ close, refresh }) { const [form, setForm] = useState({ name: '', slug: '', type: 'restaurant', logoUrl: '' }); const [error, setError] = useState(''); const submit = async (event) => { event.preventDefault(); try { await api.create('vendors', { ...form, displayOrder: 99 }); close(); refresh(); } catch (e) { setError(e.message); } }; return <div className="modal"><form className="modal-card" onSubmit={submit}><button type="button" className="close" onClick={close}><X /></button><p className="kicker">NEW VENDOR</p><h2>Add a vendor/service</h2><div className="form-grid"><label>Name<input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></label><label>Slug<input required value={form.slug} onChange={e => setForm({ ...form, slug: e.target.value })} /></label><label>Type<select value={form.type} onChange={e => setForm({ ...form, type: e.target.value })}><option value="restaurant">Restaurant</option><option value="get4me">GET4ME</option><option value="package_delivery">Package delivery</option></select></label><label>Logo URL<input value={form.logoUrl} onChange={e => setForm({ ...form, logoUrl: e.target.value })} placeholder="Cloudinary URL" /></label></div>{error && <p className="error">{error}</p>}<button className="primary full">Create vendor</button></form></div>; }
function CreateProduct({ close, refresh }) { const [form, setForm] = useState({ vendor: '', name: '', slug: '', category: '', description: '', price: '', imageUrl: '' }); const [error, setError] = useState(''); const change = (key) => (event) => setForm({ ...form, [key]: event.target.value }); const submit = async (event) => { event.preventDefault(); try { await api.create('products', { ...form, price: Number(form.price), displayOrder: 99 }); close(); refresh(); } catch (e) { setError(e.message); } }; return <div className="modal"><form className="modal-card" onSubmit={submit}><button type="button" className="close" onClick={close}><X /></button><p className="kicker">NEW PRODUCT</p><h2>Add a catalog item</h2><div className="form-grid"><label>Vendor ID<input required value={form.vendor} onChange={change('vendor')} placeholder="MongoDB vendor ID" /></label><label>Name<input required value={form.name} onChange={change('name')} /></label><label>Slug<input required value={form.slug} onChange={change('slug')} /></label><label>Category<input required value={form.category} onChange={change('category')} /></label><label>Price<input required min="0" type="number" value={form.price} onChange={change('price')} /></label><label>Image URL<input value={form.imageUrl} onChange={change('imageUrl')} /></label><label className="wide">Description<input value={form.description} onChange={change('description')} /></label></div>{error && <p className="error">{error}</p>}<button className="primary full">Create product</button></form></div>; }
function CreateRider({ close, refresh }) { const [form, setForm] = useState({ name: '', phone: '', username: '', password: '' }); const [error, setError] = useState(''); const change = (key) => (event) => setForm({ ...form, [key]: event.target.value }); const submit = async (event) => { event.preventDefault(); try { await api.createRider(form); close(); refresh(); } catch (e) { setError(e.message); } }; return <div className="modal"><form className="modal-card" onSubmit={submit}><button type="button" className="close" onClick={close}><X /></button><p className="kicker">NEW RIDER</p><h2>Add a rider</h2><div className="form-grid"><label>Name<input required value={form.name} onChange={change('name')} /></label><label>Phone<input required value={form.phone} onChange={change('phone')} /></label><label>Username<input required value={form.username} onChange={change('username')} /></label><label>Password<input required minLength="8" type="password" value={form.password} onChange={change('password')} /></label></div>{error && <p className="error">{error}</p>}<button className="primary full">Create rider</button></form></div>; }
function CreditFloat({ rider, close, refresh }) { const [amount, setAmount] = useState(''); const [error, setError] = useState(''); const submit = async (event) => { event.preventDefault(); try { await api.creditFloat(rider._id, { amount: Number(amount) }); close(); refresh(); } catch (e) { setError(e.message); } }; return <div className="modal"><form className="modal-card" onSubmit={submit}><button type="button" className="close" onClick={close}><X /></button><p className="kicker">RIDER FLOAT</p><h2>Fund {rider.name}</h2><p className="muted">Current balance: {money(rider.availableFloat)}</p><label>Amount<input required min="1" type="number" value={amount} onChange={e => setAmount(e.target.value)} /></label>{error && <p className="error">{error}</p>}<button className="primary full">Credit float</button></form></div>; }
function App() { const [user, setUser] = useState(null); const [section, setSection] = useState('overview'); const [data, setData] = useState(null); const [rows, setRows] = useState([]); const [modal, setModal] = useState(false); const [error, setError] = useState(''); const loadDashboard = () => api.dashboard().then(setData).catch(e => setError(e.message)); const loadRows = (resource) => api.list(resource).then(setRows).catch(e => setError(e.message)); useEffect(() => { if (user) loadDashboard(); }, [user]); useEffect(() => { const resource = section === 'requests' ? 'packages' : section; if (user && !['overview','settings'].includes(section)) loadRows(resource); }, [section, user]); if (!user) return <Login onAuthenticated={setUser} />; const logout = () => { setToken(''); setUser(null); }; const labels = { orders: 'Orders & payments', vendors: 'Vendor management', products: 'Product catalog', riders: 'Rider management', packages: 'Package delivery', requests: 'Service requests' }; return <div className="admin-shell"><Sidebar section={section} setSection={setSection} logout={logout} /><main className="admin-main"><header className="mobile-header"><button className="icon"><Menu size={20} /></button><b>PRIMESTAR ADMIN</b><span /></header>{error && <div className="error-banner">{error}<button onClick={() => setError('')}><X size={14} /></button></div>}{section === 'overview' && data && <Overview data={data} refresh={loadDashboard} />}{!['overview','settings'].includes(section) && <ResourceTable resource={section === 'requests' ? 'service requests' : section} title={labels[section]} rows={rows} onRefresh={() => loadRows(section === 'requests' ? 'packages' : section)} onCreate={section === 'vendors' ? () => setModal(true) : undefined} onAction={section === 'orders' ? (row) => api.confirmPayment(row.orderId).then(() => loadRows('orders')) : undefined} />}{section === 'settings' && <SettingsPanel />}{modal && <CreateVendor close={() => setModal(false)} refresh={() => loadRows('vendors')} />}</main></div>; }
function AdminApp() {
	const [user, setUser] = useState(null);
	const [section, setSection] = useState('overview');
	const [data, setData] = useState(null);
	const [rows, setRows] = useState([]);
	const [modal, setModal] = useState(null);
	const [error, setError] = useState('');
	const resource = section === 'requests' ? 'packages' : section;
	const loadRows = () => api.list(resource).then(setRows).catch((requestError) => setError(requestError.message));
	const loadDashboard = () => api.dashboard().then(setData).catch((requestError) => setError(requestError.message));
	const run = (operation) => operation.catch((requestError) => setError(requestError.message));
	useEffect(() => { if (user) loadDashboard(); }, [user]);
	useEffect(() => { if (user && !['overview', 'settings'].includes(section)) loadRows(); }, [section, user]);
	if (!user) return <Login onAuthenticated={setUser} />;
	const labels = { orders: 'Orders & payments', vendors: 'Vendor management', products: 'Product catalog', riders: 'Rider management', requests: 'Service requests' };
	const orderStatuses = ['Placed', 'Awaiting Payment', 'Payment Confirmed', 'Rider Assigned', 'Picked Up', 'Out for Delivery', 'Delivered'];
	const orderAction = (row) => { if (row.paymentState === 'awaiting_confirmation') return run(api.confirmPayment(row.orderId).then(loadRows)); const next = orderStatuses[orderStatuses.indexOf(row.status) + 1]; return next ? run(api.updateOrder(row.orderId, { status: next }).then(loadRows)) : undefined; };
	const logout = () => { setToken(''); setUser(null); };
	return <div className="admin-shell"><Sidebar section={section} setSection={setSection} logout={logout} /><main className="admin-main"><header className="mobile-header"><button className="icon"><Menu size={20} /></button><b>PRIMESTAR ADMIN</b><span /></header>{error && <div className="error-banner">{error}<button onClick={() => setError('')}><X size={14} /></button></div>}{section === 'overview' && data && <Overview data={data} refresh={loadDashboard} />}{!['overview', 'settings'].includes(section) && <ResourceTable resource={section === 'requests' ? 'service requests' : section} title={labels[section]} rows={rows} onRefresh={loadRows} onCreate={section === 'vendors' ? () => setModal('vendor') : section === 'products' ? () => setModal('product') : section === 'riders' ? () => setModal('rider') : undefined} onAction={section === 'orders' ? orderAction : section === 'riders' ? (row) => setModal({ type: 'float', rider: row }) : undefined} />}{section === 'settings' && <SettingsPanel />}{modal === 'vendor' && <CreateVendor close={() => setModal(null)} refresh={loadRows} />}{modal === 'product' && <CreateProduct close={() => setModal(null)} refresh={loadRows} />}{modal === 'rider' && <CreateRider close={() => setModal(null)} refresh={loadRows} />}{modal?.type === 'float' && <CreditFloat rider={modal.rider} close={() => setModal(null)} refresh={loadRows} />}</main></div>;
}
createRoot(document.getElementById('root')).render(<AdminApp />);
