import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowRight, Bike, Check, ChevronDown, ChevronUp, Clock3, LogOut, MapPin, Package, Phone, RefreshCw, Wallet, Wifi, WifiOff } from 'lucide-react';
import { api, hasToken, setToken } from './api';
import './style.css';

const money = (value) => `₦${Number(value || 0).toLocaleString('en-NG')}`;
const statusSteps = { 'Rider Assigned': 'Picked Up', 'Picked Up': 'Out for Delivery', 'Out for Delivery': 'Delivered' };

function Login({ onLogin }) {
  const [form, setForm] = useState({ username: '', password: '' });
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  const submit = async (event) => { event.preventDefault(); setBusy(true); setError(''); try { const result = await api.login(form); setToken(result.accessToken); onLogin(result.user); } catch (requestError) { setError(requestError.message); } finally { setBusy(false); } };
  return <main className="login-shell"><section className="login-card"><div className="brand-mark"><Bike size={22} /></div><p className="eyebrow">PRIMESTAR / RIDER</p><h1>Ready for the road?</h1><p className="muted">Sign in with the rider account created for you by PRIMESTAR.</p><form onSubmit={submit}><label>Username<input required autoComplete="username" value={form.username} onChange={(event) => setForm({ ...form, username: event.target.value })} /></label><label>Password<input required type="password" autoComplete="current-password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} /></label>{error && <p className="error">{error}</p>}<button className="button button-gold" disabled={busy}>{busy ? 'Signing in...' : 'Sign in'} <ArrowRight size={17} /></button></form></section></main>;
}

function StatusPill({ status }) { return <span className={`status-pill status-${status.toLowerCase().replaceAll(' ', '-')}`}>{status}</span>; }
function OrderCard({ order, onStatus, busy }) {
  const [expanded, setExpanded] = useState(false);
  const nextStatus = statusSteps[order.status];
  const customer = order.guestCustomer || order.customer || {};
  return <article className="order-card"><div className="order-top"><div><p className="eyebrow">ORDER</p><h2>{order.orderId}</h2><StatusPill status={order.status} /></div><button className="icon-button" onClick={() => setExpanded(!expanded)} aria-label={expanded ? 'Collapse order' : 'Expand order'}>{expanded ? <ChevronUp size={19} /> : <ChevronDown size={19} />}</button></div><div className="customer-row"><div><strong>{customer.name || 'Customer'}</strong><span>{customer.phone || 'No phone listed'}</span></div>{customer.phone && <a className="icon-button call" href={`tel:${customer.phone}`} aria-label={`Call ${customer.name || 'customer'}`}><Phone size={17} /></a>}</div><div className="delivery-destination"><MapPin size={18} /><div><strong>{order.deliveryLocation?.address || 'Address unavailable'}</strong><span>{[order.deliveryLocation?.area, order.deliveryLocation?.landmark].filter(Boolean).join(' · ')}</span></div></div>{expanded && <div className="order-details"><section><h3>Pickup plan</h3>{(order.pickupStops?.length ? order.pickupStops : order.vendors || []).map((stop, index) => <div className="pickup-stop" key={stop._id || `${stop}-${index}`}><span>{index + 1}</span><div><strong>{stop.name || 'Vendor pickup'}</strong><small>{stop.address || stop.type || 'Confirm pickup location with dispatch'}</small></div></div>)}</section><section><h3>Items</h3>{order.items?.map((item, index) => <div className="item-row" key={`${item.product}-${index}`}><span>{item.quantity} × {item.name}</span><strong>{money(item.subtotal)}</strong><small>{item.vendor?.name || 'Vendor pickup'}</small></div>)}</section>{order.notes && <section className="note"><h3>Delivery note</h3><p>{order.notes}</p></section>}<div className="totals"><span>Items <b>{money(order.itemSubtotal)}</b></span><span>Delivery <b>{money(order.deliveryFee)}</b></span><strong>Total <b>{money(order.grandTotal)}</b></strong></div></div>}{nextStatus && <button className="button button-navy full" disabled={busy} onClick={() => onStatus(order, nextStatus)}>{busy ? 'Updating...' : `Mark ${nextStatus}`} <Check size={17} /></button>}</article>;
}

function FloatPanel({ data }) { return <section className="float-panel"><div className="section-heading"><div><p className="eyebrow">FLOAT WALLET</p><h2>Available balance</h2></div><Wallet size={20} /></div><strong className="balance">{money(data?.balance)}</strong>{data?.entries?.length ? <div className="ledger">{data.entries.slice(0, 4).map((entry) => <div className="ledger-row" key={entry._id}><span className={entry.transactionType === 'debit' ? 'debit' : 'credit'}>{entry.transactionType === 'debit' ? '-' : '+'}{money(entry.amount)}</span><div><strong>{entry.description}</strong><small>{new Date(entry.createdAt).toLocaleDateString('en-NG')}</small></div></div>)}</div> : <p className="muted">No float activity yet.</p>}</section>; }

function Dashboard({ rider, onLogout }) {
  const [orders, setOrders] = useState([]); const [float, setFloat] = useState(null); const [online, setOnline] = useState(Boolean(rider.online)); const [busyId, setBusyId] = useState(''); const [error, setError] = useState(''); const [refreshing, setRefreshing] = useState(false);
  const load = async () => { setRefreshing(true); setError(''); try { const [assigned, wallet, profile] = await Promise.all([api.orders(), api.float(), api.me()]); setOrders(assigned); setFloat(wallet); setOnline(Boolean(profile.online)); } catch (requestError) { if (requestError.code === 'UNAUTHORIZED') onLogout(); else setError(requestError.message); } finally { setRefreshing(false); } };
  useEffect(() => { load(); }, []);
  const toggleOnline = async () => { try { const result = await api.setOnline(!online); setOnline(result.online); } catch (requestError) { setError(requestError.message); } };
  const updateStatus = async (order, status) => { setBusyId(order.orderId); setError(''); try { await api.updateOrder(order.orderId, status); await load(); } catch (requestError) { setError(requestError.message); } finally { setBusyId(''); } };
  return <main className="app-shell"><header className="topbar"><div className="brand"><span className="brand-mark small"><Bike size={17} /></span><div><strong>PRIMESTAR</strong><small>RIDER / CONTROL</small></div></div><button className="icon-button" onClick={onLogout} aria-label="Sign out"><LogOut size={18} /></button></header><div className="content"><section className="welcome"><div><p className="eyebrow">GOOD MORNING</p><h1>{rider.name || rider.username}</h1><p className="muted">Your next route, at a glance.</p></div><button className={`online-toggle ${online ? 'is-online' : ''}`} onClick={toggleOnline}>{online ? <Wifi size={17} /> : <WifiOff size={17} />}<span>{online ? 'Online' : 'Offline'}</span></button></section>{error && <div className="error-banner">{error}</div>}<div className="quick-grid"><div><Wallet size={18} /><small>Float balance</small><strong>{money(float?.balance ?? rider.availableFloat)}</strong></div><div><Package size={18} /><small>Active orders</small><strong>{orders.length}</strong></div></div><FloatPanel data={float} /><section className="orders-section"><div className="section-heading"><div><p className="eyebrow">YOUR ROUTE</p><h2>Assigned orders</h2></div><button className="icon-button" onClick={load} disabled={refreshing} aria-label="Refresh orders"><RefreshCw size={18} className={refreshing ? 'spin' : ''} /></button></div>{orders.length ? orders.map((order) => <OrderCard key={order.orderId} order={order} onStatus={updateStatus} busy={busyId === order.orderId} />) : <div className="empty-state"><Clock3 size={25} /><h3>No active deliveries</h3><p>New assigned orders will appear here.</p></div>}</section></div></main>;
}

function App() { const [rider, setRider] = useState(null); const [checking, setChecking] = useState(hasToken()); useEffect(() => { if (!hasToken()) { setChecking(false); return; } api.me().then(setRider).catch(() => setToken('')).finally(() => setChecking(false)); }, []); const logout = () => { setToken(''); setRider(null); }; if (checking) return <div className="loading">Loading rider workspace...</div>; return rider ? <Dashboard rider={rider} onLogout={logout} /> : <Login onLogin={setRider} />; }
createRoot(document.getElementById('root')).render(<App />);
