const Vendor = require('../models/Vendor');
const Product = require('../models/Product');
const Order = require('../models/Order');
const Rider = require('../models/Rider');
const FloatLedger = require('../models/FloatLedger');
const Zone = require('../models/Zone');
const FormulaSettings = require('../models/FormulaSettings');
const PackageDeliveryRequest = require('../models/PackageDeliveryRequest');
const Get4MeRequest = require('../models/Get4MeRequest');
const Customer = require('../models/Customer');
const { hashPassword } = require('../utils/auth');
const { success } = require('../utils/api');

const models = { vendors: Vendor, products: Product, orders: Order, riders: Rider, packages: PackageDeliveryRequest, get4me: Get4MeRequest, customers: Customer, zones: Zone };
function list(Model, query = {}, populate) { let request = Model.find(query).sort({ createdAt: -1 }); if (populate) request = request.populate(populate); return request; }
async function dashboard(req, res) { const [orders, pendingPayments, confirmedPayments, riders, vendors, products, packages, get4me] = await Promise.all([Order.countDocuments(), Order.countDocuments({ paymentState: 'awaiting_confirmation' }), Order.countDocuments({ paymentState: 'confirmed' }), Rider.countDocuments({ active: true, online: true }), Vendor.countDocuments({ active: true }), Product.countDocuments(), PackageDeliveryRequest.countDocuments({ status: { $nin: ['delivered', 'cancelled'] } }), Get4MeRequest.countDocuments({ status: { $nin: ['completed', 'cancelled'] } })]); return success(res, { orders, pendingPayments, confirmedPayments, activeRiders: riders, vendors, products, packageRequests: packages, get4meRequests: get4me }); }
async function listResource(req, res) { const Model = models[req.params.resource]; if (!Model) return res.status(404).json({ success: false, error: { message: 'Resource not found' } }); const populate = req.params.resource === 'orders' ? [{ path: 'customer', select: 'name phone email' }, { path: 'rider', select: 'name username online availableFloat' }] : req.params.resource === 'products' ? 'vendor' : req.params.resource === 'get4me' ? 'vendor' : undefined; return success(res, await list(Model, {}, populate)); }
async function createResource(req, res) { const Model = models[req.params.resource]; if (!Model || !['vendors', 'products', 'zones'].includes(req.params.resource)) return res.status(404).json({ success: false, error: { message: 'Resource not found' } }); return success(res, await Model.create(req.body), 201); }
async function updateResource(req, res) { const Model = models[req.params.resource]; if (!Model || !['vendors', 'products', 'zones', 'packages', 'get4me', 'riders'].includes(req.params.resource)) return res.status(404).json({ success: false, error: { message: 'Resource not found' } }); const value = await Model.findByIdAndUpdate(req.params.id, req.body, { new: true, runValidators: true }); if (!value) return res.status(404).json({ success: false, error: { message: 'Record not found' } }); return success(res, value); }
async function createRider(req, res) { const { password, ...details } = req.body; return success(res, await Rider.create({ ...details, passwordHash: await hashPassword(password) }), 201); }
async function creditFloat(req, res) { const rider = await Rider.findById(req.params.id); if (!rider) return res.status(404).json({ success: false, error: { message: 'Rider not found' } }); const amount = Number(req.body.amount); if (!Number.isFinite(amount) || amount <= 0) return res.status(422).json({ success: false, error: { message: 'Amount must be greater than zero' } }); const before = rider.availableFloat; rider.availableFloat += amount; await rider.save(); const entry = await FloatLedger.create({ rider: rider._id, transactionType: 'credit', amount, balanceBefore: before, balanceAfter: rider.availableFloat, description: req.body.description || 'Admin float funding', reference: req.auth.user.username }); return success(res, { rider, ledger: entry }); }
async function confirmPayment(req, res) { const order = await Order.findOneAndUpdate({ orderId: req.params.orderId }, { paymentState: 'confirmed', status: 'Payment Confirmed', paymentConfirmedAt: new Date() }, { new: true }); if (!order) return res.status(404).json({ success: false, error: { message: 'Order not found' } }); return success(res, order); }
async function updateOrder(req, res) { const allowed = ['Placed', 'Awaiting Payment', 'Payment Confirmed', 'Rider Assigned', 'Picked Up', 'Out for Delivery', 'Delivered', 'Cancelled', 'Expired']; if (req.body.status && !allowed.includes(req.body.status)) return res.status(422).json({ success: false, error: { message: 'Invalid order status' } }); const order = await Order.findOneAndUpdate({ orderId: req.params.orderId }, req.body, { new: true, runValidators: true }); if (!order) return res.status(404).json({ success: false, error: { message: 'Order not found' } }); return success(res, order); }
async function getSettings(req, res) { return success(res, await FormulaSettings.findOne() || { baseFee: 0, perKilometreRate: 0, active: true }); }
async function updateSettings(req, res) { return success(res, await FormulaSettings.findOneAndUpdate({}, req.body, { upsert: true, new: true, runValidators: true })); }
module.exports = { dashboard, listResource, createResource, updateResource, createRider, creditFloat, confirmPayment, updateOrder, getSettings, updateSettings };
