const Admin = require('../models/Admin');
const Customer = require('../models/Customer');
const Rider = require('../models/Rider');
const { hashPassword, comparePassword, signAccessToken, signRefreshToken, generateOtp, hashToken } = require('../utils/auth');
const { sendEmail } = require('../config/email');
const { success } = require('../utils/api');
function tokens(user, type) { const payload = { sub: user._id.toString(), type, role: user.role }; return { accessToken: signAccessToken(payload), refreshToken: signRefreshToken(payload) }; }
function safe(user) { const value = user.toObject ? user.toObject() : { ...user }; delete value.passwordHash; delete value.otpHash; delete value.passwordResetHash; return value; }
async function customerSignup(req, res) { const { name, phone, email, username, password } = req.body; const customer = await Customer.create({ name, phone, email, username, passwordHash: await hashPassword(password) }); return success(res, { user: safe(customer), ...tokens(customer, 'customer') }, 201); }
async function customerLogin(req, res) { const customer = await Customer.findOne({ username: req.body.username }).select('+passwordHash'); if (!customer || !(await comparePassword(req.body.password, customer.passwordHash))) return res.status(401).json({ success: false, error: { message: 'Invalid credentials' } }); return success(res, { user: safe(customer), ...tokens(customer, 'customer') }); }
async function riderLogin(req, res) { const rider = await Rider.findOne({ username: req.body.username }).select('+passwordHash'); if (!rider || !(await comparePassword(req.body.password, rider.passwordHash))) return res.status(401).json({ success: false, error: { message: 'Invalid credentials' } }); return success(res, { user: safe(rider), ...tokens(rider, 'rider') }); }
async function adminLogin(req, res) { const admin = await Admin.findOne({ username: req.body.username }).select('+passwordHash +otpHash'); if (!admin || !(await comparePassword(req.body.password, admin.passwordHash))) return res.status(401).json({ success: false, error: { message: 'Invalid credentials' } }); const otp = generateOtp(); admin.otpHash = hashToken(otp); admin.otpExpiresAt = new Date(Date.now() + 10 * 60 * 1000); admin.otpAttempts = 0; admin.otpSentAt = new Date(); await admin.save(); try { await sendEmail({ to: admin.email, subject: 'PRIMESTAR admin verification code', text: `Your verification code is ${otp}. It expires in 10 minutes.` }); } catch { admin.otpHash = undefined; admin.otpExpiresAt = undefined; admin.otpAttempts = 0; admin.otpSentAt = undefined; try { await admin.save(); } catch {} return res.status(503).json({ success: false, error: { message: 'Temporarily unavailable' } }); } return success(res, { requiresOtp: true }); }
async function verifyAdminOtp(req, res) { const admin = await Admin.findOne({ username: req.body.username }).select('+otpHash'); const invalid = !admin || !admin.otpHash || admin.otpExpiresAt < new Date() || admin.otpAttempts >= 5 || admin.otpHash !== hashToken(req.body.otp); if (invalid) { if (admin && admin.otpHash) { admin.otpAttempts += 1; await admin.save(); } return res.status(401).json({ success: false, error: { message: 'Invalid or expired OTP' } }); } admin.otpHash = undefined; admin.otpExpiresAt = undefined; admin.otpAttempts = 0; await admin.save(); return success(res, { user: safe(admin), ...tokens(admin, 'admin') }); }
module.exports = { customerSignup, customerLogin, riderLogin, adminLogin, verifyAdminOtp };
