const Product = require('../models/Product');
const Order = require('../models/Order');
const { createOrderId } = require('../services/orderService');
const { success } = require('../utils/api');
async function createOrder(req, res) { const { items, deliveryLocation, guestCustomer, notes } = req.body; if (!Array.isArray(items) || !items.length) return res.status(422).json({ success: false, error: { message: 'At least one item is required' } }); const products = await Product.find({ _id: { $in: items.map((item) => item.product) }, available: true }); const byId = new Map(products.map((product) => [product._id.toString(), product])); const orderItems = items.map((item) => { const product = byId.get(String(item.product)); if (!product) throw Object.assign(new Error('Product is unavailable'), { statusCode: 400 }); const quantity = Number(item.quantity); if (!Number.isInteger(quantity) || quantity < 1) throw Object.assign(new Error('Invalid quantity'), { statusCode: 422 }); return { product: product._id, vendor: product.vendor, name: product.name, quantity, unitPrice: product.price, subtotal: product.price * quantity }; }); const itemSubtotal = orderItems.reduce((sum, item) => sum + item.subtotal, 0); const vendorIds = [...new Set(orderItems.map((item) => item.vendor.toString()))]; const order = await Order.create({ orderId: createOrderId(), customer: req.auth?.type === 'customer' ? req.auth.sub : undefined, guestCustomer, vendors: vendorIds, items: orderItems, deliveryLocation, itemSubtotal, deliveryFee: 0, grandTotal: itemSubtotal, status: 'Placed', notes }); return success(res, order, 201); }
async function submitPayment(req, res) { const order = await Order.findOneAndUpdate({ orderId: req.params.orderId, status: { $in: ['Placed', 'Awaiting Payment'] } }, { status: 'Awaiting Payment', paymentState: 'awaiting_confirmation', paymentSubmittedAt: new Date() }, { new: true }); if (!order) return res.status(404).json({ success: false, error: { message: 'Order not found or not payable' } }); return success(res, order); }
async function confirmPayment(req, res) { const order = await Order.findOneAndUpdate({ orderId: req.params.orderId }, { status: 'Payment Confirmed', paymentState: 'confirmed', paymentConfirmedAt: new Date() }, { new: true }); if (!order) return res.status(404).json({ success: false, error: { message: 'Order not found' } }); return success(res, order); }
async function getOrder(req, res) { const order = await Order.findOne({ orderId: req.params.orderId }); if (!order) return res.status(404).json({ success: false, error: { message: 'Order not found' } }); return success(res, order); }
module.exports = { createOrder, submitPayment, confirmPayment, getOrder };
